import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Header } from "../components/Header";
import Image from "next/image";
import IconEllipsBg from "@/assets/icons/ellips-top-bg.svg";

const archivo = Archivo({
  display: "swap",
  subsets: ["latin"],
  weight: ["400","600", "700", "800", "900"],
  variable: "--font-family",
});

const gilroy = localFont({
  src: [
    {
      path: "../../public/fonts/Gilroy-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/Gilroy-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
  {
      path: "../../public/fonts/Gilroy-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-third",
});

const konnect = localFont({
  src: [
    {
      path: "../../public/fonts/KonnectMedium.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/KonnectRegular.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-second",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${archivo.className} ${gilroy.variable} ${konnect.variable} relative antialiased`}
      >
        <Header />
        <div className="relative z-10 pt-32 3xl:pt-52 overflow-x-hidden">
          {children}
        </div>
        {/* BG Image */}

        <div className="absolute inset-0  overflow-hidden">
          <div className=" absolute top-0 sm:-top-12 3xl:top-0 w-[1038px] sm:w-full 3xl:!w-[calc(100%-20px)] sm:h-[372px] max-w-[1880px] left-1/2 transform -translate-x-1/2 mix-blend-color-dodge">
            <Image
              src="/images/bg-grid_img.webp"
              alt=""
              width={1278}
              height={372}
              className="w-full h-auto"
            />
            <Image
              src="/images/bg-grid_img.webp"
              alt=""
              width={1278}
              height={372}
              className="sm:hidden w-full h-auto rotate-180"
            />

            <IconEllipsBg className="hidden sm:block absolute blur-[125px] sm:blur-[125px] sm:top-[219px] 2xl:top-[186px] w-[425px] sm:w-[645px] h-[376px] left-1/2 transform -translate-x-1/2" />
          </div>
        </div>
      </body>
    </html>
  );
}
