import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Header } from "../components/Header";

const archivo = Archivo({
  display: "swap",
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  variable: "--font-family",
});

const gilroy = localFont({
  src: [
    {
      path: "../../public/fonts/Gilroy-Medium.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/Gilroy-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-third",
});

const konnect = localFont({
  src: [
    {
      path: "../../public/fonts/KonnectMedium.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/KonnectRegular.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-second",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 2xl:aspect-[552px]  xl:aspect-[1278.01/482] 2xl:aspect-[1278.01/482] lg:h-[372px]

  return (
    <html lang="en">
      <body
        className={`${archivo.className} ${gilroy.variable} ${konnect.variable} antialiased`}
      >
        <Header />
        <div className="relative z-10 flex flex-col flex-grow items-start w-full pt-32">
          {children}
        </div>
        {/* BG Image */}
        <div className="absolute -top-10 w-[1278px] h-[302px] xl:w-[1720px] xl:h-[402px]  left-1/2 transform -translate-x-1/2  bg-[url('/images/bg-grid_img.webp')] bg-[length:100%_118.961%] bg-[position:0_-70.597px] bg-no-repeat mix-blend-color-dodge"></div>
      </body>
    </html>
  );
}
