import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Header } from "../components/Header";
import Image from "next/image";

const archivo = Archivo({
  display: "swap",
  subsets: ["latin"],
  weight: ["400","600", "700", "900"],
  variable: "--font-family",
});

const gilroy = localFont({
  src: [
    {
      path: "../../public/fonts/Gilroy-Medium.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/Gilroy-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
  {
      path: "../../public/fonts/Gilroy-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-third",
});

const konnect = localFont({
  src: [
    {
      path: "../../public/fonts/KonnectMedium.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/KonnectRegular.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-second",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 2xl:aspect-[552px]  xl:aspect-[1278.01/482] 2xl:aspect-[1278.01/482] lg:h-[372px]

  return (
    <html lang="en">
      <body
        className={`${archivo.className} ${gilroy.variable} ${konnect.variable} relative antialiased`}
      >
        <Header />
        <div className="relative z-10 pt-32">{children}</div>
        {/* BG Image */}
        <Image src="/images/bg-grid_img.webp" alt="" width={1720} height={402} className="absolute -top-10 w-full h-auto left-1/2 transform -translate-x-1/2  mix-blend-color-dodge" />
      </body>
    </html>
  );
}
